services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crawl_data_express
      MYSQL_USER: hieunk
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"  # Cổng mặc định của Redis
    volumes:
      - redis_data:/data
  spider-cron:
    build: .                  # Chỉ định thư mục hiện tại làm context build Docker
    container_name: spider-cron
    volumes:
      - .:/app                 # Mount thư mục hiện tại vào thư mục /app trong container
    command: cron -f
volumes:
  mysql_data:
  redis_data:
    
